server:
  port: 8080

spring:
  datasource:
    url:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace


objects-storage.endPoint: https://kr.object.ncloudstorage.com
objects-storage.regionName: kr-standard
objects-storage.accessKey:
objects-storage.secretKey:
objects-storage.bucketName: i